### ISSUE TITLE
Error	C2397	conversion from 'vx_int32' to 'vx_uint32' requires a narrowing conversion

### ISSUE THREAD

**Issue by xqch1983** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#1]
error report : 
  Severity  Code    Description Project File    Line
Error   C2397   conversion from 'vx_int32' to 'vx_uint32' requires a narrowing conversion   vx_loomsl   .  .\amdovx-modules-master\vx_loomsl\kernels\multiband_blender.cpp  395

solution :  multiband_blender.cpp
   376:     vx_int32 x1, y1, x2, y2;  be changed to 
   376:     vx_uint32 x1, y1, x2, y2; 

is it a bug?

platform : vs2015  win64  
compiler :  vs2015 defaulter compiler.

**Comment by rgiduthuri** [comment]
This shouldn't be a bug as the values get clamped to unsigned values before assignment to vx_uint32. We should add a type case to avoid compiler warnings. :+1: 

Thanks
