### ISSUE TITLE
./loom_shell: symbol lookup error pthreads.

### ISSUE THREAD

**Issue by javierox** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#100]
Hi ! 

/loom_shell: symbol lookup error: /home/rocm-user/amdovx-modules/build/bin/libvx_loomsl.so: undefined symbol: pthread_create

uname -a
Linux 4ed660a634d9 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ nm /lib/libpthread_.so | grep pthread_create
nm: '/lib/libpthread_.so': No such file

$ for i in /lib /lib32 /lib64 ; do

    find $i -name 'libpthread_.so_'
    find /usr/$i -name 'libpthread_.so_'
    done
    /lib/x86_64-linux-gnu/libpthread-2.23.so
    /lib/x86_64-linux-gnu/libpthread.so.0
    /usr//lib/x86_64-linux-gnu/libpthread.so 
    find: /lib32': No such file or directory find:/usr//lib32': No such file or directory
    find: `/usr//lib64': No such file or directory

$ objdump -T /lib/x86_64-linux-gnu/libpthread-2.23.so | grep pthread_create
0000000000007990 g    DF .text	0000000000000e88  GLIBC_2.2.5 pthread_create

$ ldd which libvx_loomsl.so

libvx_loomsl.so:
	linux-vdso.so.1 =>  (0x00007ffe8b7bb000)
	libOpenCL.so.1 => /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 (0x00007f0fe72e9000)
	libopenvx.so => /home/rocm-user/amdovx-modules/build/bin/libopenvx.so (0x00007f0fe6ec1000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0fe6b39000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0fe6829000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0fe6611000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0fe6241000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0fe6039000)
	/lib64/ld-linux-x86-64.so.2 (0x0000563113503000)

Any ideas what's wrong?, maybe gcc link order?

**Comment by javierox** [comment]
A temporary solution is add pthread to target_link_libraries in CmakeLists on loomsheel directory.

**Comment by rgiduthuri** [comment]
Hi @javierox, Would the following change fix the problem? If not, could you please submit a pull request with the change? Thx
````
$ git diff
diff --git a/utils/loom_shell/CMakeLists.txt b/utils/loom_shell/CMakeLists.txt
index d01be32..33c8034 100644
--- a/utils/loom_shell/CMakeLists.txt
+++ b/utils/loom_shell/CMakeLists.txt
@@ -52,4 +52,5 @@ if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
        set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /MTd")
 else()
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
+       target_link_libraries(loom_shell pthread)
 endif()
````

**Comment by rgiduthuri** [comment]
The recent commit takes care of this...
