### ISSUE TITLE
 memory leak found in stitchInitCalcCamWarpMaps node

### ISSUE THREAD

**Issue by cha007** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#104]
stitchInitCalcCamWarpMaps 
	vx_scalar scCamId = vxCreateScalar(vxGetContext((vx_reference)graph), VX_TYPE_UINT32, &cam_warp->camId);
	vx_scalar scLensType = vxCreateScalar(vxGetContext((vx_reference)graph), VX_TYPE_UINT32, &cam_warp->lens_type);
	vx_scalar scCamW = vxCreateScalar(vxGetContext((vx_reference)graph), VX_TYPE_UINT32, &cam_warp->camWidth);
	vx_scalar scCamH = vxCreateScalar(vxGetContext((vx_reference)graph), VX_TYPE_UINT32, &cam_warp->camHeight);
	vx_scalar scPadCnt = vxCreateScalar(vxGetContext((vx_reference)graph), VX_TYPE_UINT32, &cam_warp->paddingPixelCount);
	not call vxReleaseScalar after create the node

**Comment by rgiduthuri** [comment]
@cha007 Thanks for catching this.. If you already have a fix and would like to contribute, please submit a pull request.
