### ISSUE TITLE
ERROR: The BMP format is not supported or dimensions doesn't match buffer size in CAM00.bmp

### ISSUE THREAD

**Issue by arpu** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#11]
i always get this error can you share your test CAM00.bmp?

**Comment by arpu** [comment]
https://drive.google.com/open?id=0B1Gn13Bs6VLTb0h0SGFjWHJMcGc
my not working testfile

**Comment by arpu** [comment]
i testing with this sample Example #1: Simple Example
https://github.com/GPUOpen-ProfessionalCompute-Libraries/amdovx-modules/blob/master/utils/loom_shell/README.md

**Comment by arpu** [comment]
i add some more debug infos and i get 
4D42 138 1 24  in 6220800 for 
 Error("ERROR: %02X %d %d %d  in %d\n", bmpHeader[0], bmpHeader[5], bmpHeader[13], bmpHeader[14], size);

so it looks like the  bmpHeader[5] is wrong?

**Comment by gshisha** [comment]
I've uploaded a sample bmp to verify on your side.
https://amd.box.com/s/z4kmlp5my229ker15jicsd6ggbf0b3ii

What tool did you use to convert the jpg to bmp? I usually use irfanview.

**Comment by arpu** [comment]
thx a lot 
loading this bmp works fine!
i use fedora 25 and tested with gimp or convert from ImageMagick 6.9.3-0
