### ISSUE TITLE
[Question] Run inference generator with Imagenet Caffe model

### ISSUE THREAD

**Issue by jo-ilg** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#115]
Hi, 
during my research work, i tried to run the inference generator wigh a [NIN-Imagenet pretrained model](https://github.com/BVLC/caffe/wiki/Model-Zoo). The goal was to generate openVX code and analyse the generated openVX code on hardware independency.

The problem is, during the weight fetching a exception of protobuf throws:

![exception](https://user-images.githubusercontent.com/25639964/32166135-48474b6e-bd65-11e7-91dd-5b39349fe9df.PNG)

My questions are: 

- Is it fundementally possible to run the inference_generator with such kinds of neural networks like alexnet or Imagenet and do you know a fix for the exception above?
- Is there a possibility to generate neural network openVX code, which is essential independently from hardware vendors? (Without the need of the AMD specific vx_ext_amd header.)

**Comment by rgiduthuri** [comment]
Hi, 

We’re looking into adding group support into inference generator — for alexnet. 

OpenVX vx_khr_nn spec currently doesn’t support floating point, so not all vendors support float. Quantization in inference generator is not supported yet — this is required for interoperability. You should be able to modify the code to make it interoperable by adding quantization and generate code constrained to vx_khr_nn.

**Comment by rgiduthuri** [comment]
One more thing: you need to upgrade the prototxt and caffemodel using caffe tools as current version of inference generator doesn’t support of V1Layer.

**Comment by rgiduthuri** [comment]
Also try to give the input tensor dimensions on the inference generator command line.

**Comment by jo-ilg** [comment]
Thanks @rgiduthuri for your response. 
I`m still working for the work-around for interoperability.

I tried to run a cifar10 trained model with the inference generator and it was generated after i gave the input tensor dimension on the inference generator and upgrade the caffemodel. Thanks for the hint!

But now i have a problem with runvx to generate a input.f32 from a picture. I tried to run the following gdf example:
```
import vx_nn
data input  = image:32,32,RGB2
data output = tensor:4,{32,32,3,1},VX_TYPE_FLOAT32,0
data a = scalar:FLOAT32,0.0
data b = scalar:FLOAT32,0.0
data reverse_channel_order = scalar:BOOL,0
read input pic.png
node com.amd.nn_extension.convert_image_to_tensor input output a b reverse_channel_order
write output input.f32
```
But receive the following Error:
![unbenannt](https://user-images.githubusercontent.com/25639964/32355042-dc68f36e-c02c-11e7-8897-a05ca49ecd52.PNG)

I installed opencv 3.0 and the OpenCV_DIR environment variable is pointed to the build directory. Do you know a opportunity to fix the error?

**Comment by rgiduthuri** [comment]
Please attach pic.png so that we can try to reproduce the issue.
Also try with the latest code in develop branch.

**Comment by arpu** [comment]
looks like a opencv problem try install latest stable OpenCV 3.3 (with libpng support) or git master 
and/or wrong pic.png

**Comment by rgiduthuri** [comment]
Thx @arpu
