### ISSUE TITLE
How good is this stitch?

### ISSUE THREAD

**Issue by moshest** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#15]
A made a simple test and got the following result:

![output](https://cloud.githubusercontent.com/assets/534911/25433026/9bb0e3a0-2a8f-11e7-95c8-7d7cc8a55edd.jpg)

I test it with a complete ptgui `.pts` file or with plan hard-coded stitch configuration, both give me the same result witch is not so good comparing to ptgui stitch or other softwares.

**Comment by gshisha** [comment]
Would you be able to share the loom script and if possible, the ptgui file...?

**Comment by moshest** [comment]
I attach here the .cpp file and the .pts file: [Archive.zip](https://github.com/GPUOpen-ProfessionalCompute-Libraries/amdovx-modules/files/958884/Archive.zip)

I used the example code as I saw in the docs.
Here is the cameras configuration (full code on the zip):
```c++
// values from the .pts file
float v = 176.8733725649175;
float haw = ((float) cWidth) * 1;
float r_crop = haw / 2;
float a = 0;
float b = -0.1722779181005715;
float c = 0;

// define camera orientation and lens parameters
// {{yaw,pitch,roll,tx,ty,tz},{hfov,haw,r_crop,du0,dv0,lens_type,k1,k2,k3}};
camera_params cam1_par = { { -90,0,-90,0,0,0 },{ v,haw,r_crop,0,0,ptgui_lens_fisheye_circ,a,b,c } };
camera_params cam2_par = { { 0,0,-90,0,0,0 },{ v,haw,r_crop,0,0,ptgui_lens_fisheye_circ,a,b,c } };
camera_params cam3_par = { { 90,0,-90,0,0,0 },{ v,haw,r_crop,0,0,ptgui_lens_fisheye_circ,a,b,c } };
camera_params cam4_par = { { 180,0,-90,0,0,0 },{ v,haw,r_crop,0,0,ptgui_lens_fisheye_circ,a,b,c } };
```

**Comment by arpu** [comment]
@moshest can you upload the sample images files? 
the four CAM%02d.bmp and what gpu and operation system do you use?

**Comment by moshest** [comment]
Images [attached](https://github.com/GPUOpen-ProfessionalCompute-Libraries/amdovx-modules/files/1101697/CAM.zip). I'm using windows 10 machine with GPU GV-RX480G1

**Comment by kiritigowda** [comment]
Hi @moshest  I suggest you try with a sample from PTgui which can be found here https://www.ptgui.com/images/vigntutorial/vigntutorial.zip along with the attached loom shell script.
[PTgui.txt](https://github.com/GPUOpen-ProfessionalCompute-Libraries/amdovx-modules/files/1113035/PTgui.txt)

**Comment by kiritigowda** [comment]
Hi @moshest were you able to run the test case or did you need any help?

**Comment by moshest** [comment]
I have no time to try it yet.

Suppose it's works fine for me, then what?
What's wrong with my configuration and why PTGui makes perfect stitch despite that?

**Comment by kiritigowda** [comment]
@moshest here is the PTgui output for your .pts file. 
![ptgui-github_example_stitch](https://user-images.githubusercontent.com/16549273/27928168-006a800e-6243-11e7-9a70-729db133654b.jpg)

is this the stitch your comparing? else please upload the image you are using for comparison.

**Comment by kiritigowda** [comment]
Loom output for the above test images. 
![loomoutputstitch](https://user-images.githubusercontent.com/16549273/27932481-bf379544-6252-11e7-9a20-0a46ff1c6209.jpg)

**Comment by moshest** [comment]
That's a great output! Exactly I saw on the PTGui.
Can you send me your code that generate it so I can compare it with my own?

**Comment by kiritigowda** [comment]
@moshest I have attached the full test, which contains loom shell script, ptgui .pts file and images. I did not have time to fine tune the calibration, that's something you could work on. Use the example I gave you above to see how to get good calibration.

[github_test.zip](https://github.com/GPUOpen-ProfessionalCompute-Libraries/amdovx-modules/files/1131963/github_test.zip)

**Comment by moshest** [comment]
Thank you. I will try it an a few days and let you know.

**Comment by kiritigowda** [comment]
Hi @moshest, is your issue resolved? can we close this issue?

**Comment by moshest** [comment]
Thanks for follow up. Unfortunately I don't have the time to test it right now.
I'm closing the issue and I will open a new one if there is any problem again.

Thank you.
