### ISSUE TITLE
[Question] QT GUI Loom not possible

### ISSUE THREAD

**Issue by arpu** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#153]
i have a strange problem with loomvx and qt gui 

if i add 
 QCoreApplication app(argc, argv); 
to my main function loom cannot build the opencl kernels 
and stops with error 
```
OPENCV_OPENCL_DEVICE=LOG:[status=0] OK: OpenVX using GPU device#0 (Baffin) [OpenCL 1.2 AMD-APP (2527.3)] [SvmCaps 0 1]
LOG:[status=-1] ERROR: clBuildProgram(0x26865d0,-cl-std=CL1.2) failed(-11) for com.amd.loomsl.calc_lens_distortionwarp_map
ERROR: OpenVX call failed with status = (-1) at /home/arpu/work/githubsources/amdovx-modules/vx_loomsl/live_stitch_api.cpp#1006
ERROR: OpenVX call failed with status = (-1) at /home/arpu/work/githubsources/amdovx-modules/vx_loomsl/live_stitch_api.cpp#1058
ERROR: OpenVX call failed with status = (-1) at /home/arpu/work/githubsources/amdovx-modules/vx_loomsl/live_stitch_api.cpp#2561
```
any idea what the problem could be or how i can debug this?

without the QCoreApplication app(argc, argv);  it works

**Comment by paveltc** [comment]
Hi,

Are you seeing this problem on Windows or Linux?

Thanks,
Pavel

**Comment by arpu** [comment]
Hi 
on linux  ( ubuntu 16.04 lts) 
tested with qt version from ubuntu 5.5.1 and  qt version stable 5.10 
gcc version 5.4 and  7.2 tested

**Comment by arpu** [comment]
Any Idea what the Problem could be?

**Comment by arpu** [comment]
yeahh with help from the Qt community (thiago)  i could solve this Problem

the problem is the locale settings to LANG=de_AT.UTF-8 and here is the description from thiago

>  ok, here's what's happening: one of the things QCoreApplication does is call setlocale(LC_ALL, "");
 setlocale is a C library function that sets the locale from the environment, allowing L10N and I18N
 one of the consequences is that it changes the fraction separator from '.' to ',' in your locale
 the library you're using is likely parsing floating point with sscanf() and fails to understand the '.' from your source
 tell the library authors to use sscanf_l or some other library not affected by the global C library locale, like https://github.com/google/double-conversion

**Comment by arpu** [comment]
i will close this for now
as a good workaround starting the app with LC_ALL=C works perfect
