### ISSUE TITLE
[Doc] how use the mediaio kernel?

### ISSUE THREAD

**Issue by arpu** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#155]
how can i use the ffmpeg /vx_loomio_media for live ( 4 cameras)
stitching? cannot find any sample to use this

**Comment by arpu** [comment]
when i use 
```
        lsSetCameraModule(context, "vx_loomio_media", "com.amd.loomio_media.decode", "30,0,0,16");
        lsSetOutputModule(context, "vx_loomio_media", "com.amd.loomio_media.encode", "30,0,0");
```



building with 
g++ -std=c++11 /home/arpu/work/githubsources/amdovx-modules/utils/loom_shell/loom_shell_util.cpp  Mediaio_loom.cpp  -I/opt/rocm/include/  -lOpenCL -L/opt/rocm/lib/ -lopenvx -lvx_loomsl -lvx_loomio_media
and 
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rocm/lib/ 
./a.out

LOG:[status=-11] ERROR: Unable to load module libvx_loomio_media.so
ERROR: lsInitialize: vxLoadKernels(vx_loomio_media) failed (-11)
ERROR: OpenVX call failed with status = (-5) at /home/arpu/work/githubsources/amdovx-modules/vx_loomsl/live_stitch_api.cpp#3130

**Comment by rgiduthuri** [comment]
Check the other dependencies of vx_loomio_media and make sure they are in LD_LIBRARY_PATH

**Comment by rgiduthuri** [comment]
Hi @arpu, were you able to resolve this issue? Make sure that the vx_loomio_media is built and the shared libraries of both vx_loomio_media and ffmpeg are in LD_LIBRARY_PATH.

**Comment by rgiduthuri** [comment]
@arpu closing this the above might address the issue. please re-open if needed.
