### ISSUE TITLE
[Feature Request] custom seam  mask

### ISSUE THREAD

**Issue by arpu** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#158]
would it be possible to use a seam mask image for a custom seam stitching?

**Comment by rgiduthuri** [comment]
There is a function in live_stitch_api.h that should just do that. It takes an 8-bit blend mask (use 0 and 255 values, if a binary mask is needed).
````
//! \brief set custom blend weights.
//  - valid when seam find is not active
//  - weights: array of weights in output_width * output_height * num_camera
LIVE_STITCH_API_ENTRY vx_status VX_API_CALL lsSetBlendWeights(ls_context stitch, vx_uint8 * weights, size_t size);
````

Let me know if this addresses the issue.

**Comment by rgiduthuri** [comment]
Make sure to set `LIVE_STITCH_ATTR_SEAMFIND` attribute to 0 (i.e., to disable seam find) in order to use the `lsSetBlendWeights` API.

**Comment by rgiduthuri** [comment]
@arpu, closing this as the above answer will address the original question. Please re-open if needed.
