### ISSUE TITLE
Compiling Error on Nvidia TX2

### ISSUE THREAD

**Issue by scheng98** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#165]
Hi, 

When I tried to follow the instruction to install openVX on TX2, https://github.com/GPUOpen-ProfessionalCompute-Libraries/amdovx-modules/wiki

I got this error,
`
/49ers/sw/amdovx-modules/deps/amdovx-core/openvx/ago/ago_haf_cpu_arithmetic.cpp: In function ‘int HafCpu_Add_U8_U8U8_Wrap(vx_uint32, vx_uint32, vx_uint8*, vx_uint32, vx_uint8*, vx_uint32, vx_uint8*, vx_uint32)’: /49ers/sw/amdovx-modules/deps/amdovx-core/openvx/ago/ago_haf_cpu_arithmetic.cpp:113:2: error: ‘__m128i’ was not declared in this scope __m128i *pLocalSrc1_xmm, *pLocalSrc2_xmm, *pLocalDst_xmm;
`
Could you share how you installed openVX on TX2? thanks a lot,

Steve

**Comment by rgiduthuri** [comment]
`CPU: SSE4.1 or above CPU, 64-bit` (i.e., x86) is a pre-requisite for this project (please see README.md for full details).
