### ISSUE TITLE
https://github.com/GPUOpen-ProfessionalCompute-Libraries/amdovx-modules/blob/master/vx_opencv/OpenCV_Tunnel.h

### ISSUE THREAD

**Issue by kandoi1994** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#176]
Hello ,
In line number 77  , nullptr and element is used but not declared  so , please resolve the issue .

**Comment by rgiduthuri** [comment]
Not sure I really understood the problem. Are you pointing a problem with C++? Which compiler are you using?

**Comment by kandoi1994** [comment]
yes , Problem with c++ , I use QT Creator .

**Comment by rgiduthuri** [comment]
The nullptr is part of C++ language from C++11. I do see the definition of element. Please check your build environment. 

Unfortunately, I won't be able to help with this issue as it is a bug/feature request related to this project.

**Comment by rgiduthuri** [comment]
There was typo in my earlier comment:

Unfortunately, I won't be able to help with this issue as it is **not** a bug/feature request related to this project
