### ISSUE TITLE
How to get LoomIO plug-in?

### ISSUE THREAD

**Issue by HollyHuo** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#18]
Hi,

I want to run Real-time Live Stitch using LoomIO, so how to get the LoomIO plug-in?

Thank you!
Holly

**Comment by kiritigowda** [comment]
@HollyHuo you can reference this [document ](https://drive.google.com/file/d/0B3LydXF9N_DhY1JKRTdZdkdMWlU/view)

**Comment by rgiduthuri** [comment]
@HollyHuo let me know if you've any questions on how to build a LoomIO plug-in.
