### ISSUE TITLE
Unable to build 

### ISSUE THREAD

**Issue by srp1970** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#186]
I am getting this error when I build

Scanning dependencies of target vx_nn
make[2]: Leaving directory '/home/amd/amdovx-modules/build'
make -f vx_nn/CMakeFiles/vx_nn.dir/build.make vx_nn/CMakeFiles/vx_nn.dir/build
make[2]: Entering directory '/home/amd/amdovx-modules/build'
[ 67%] Building CXX object vx_nn/CMakeFiles/vx_nn.dir/src/kernels.cpp.o
cd /home/amd/amdovx-modules/build/vx_nn && /usr/bin/c++   -DENABLE_OPENCL=1 -Dvx_nn_EXPORTS -I/usr/include/opencv -I/home/amd/amdovx-modules/vx_nn/../deps/amdovx-core/openvx/include -I/home/amd/amdovx-modules/vx_nn/src -I/home/amd/amdovx-modules/vx_nn/include -I/home/amd/amdovx-modules/vx_nn/../utils/inference_generator -isystem /opt/rocm/include -isystem /opt/rocm/hip/include -isystem /opt/rocm/hsa/include -isystem /opt/rocm/opencl/include  -msse4.2 -std=c++11 -fPIC   -hc -fPIC -std=gnu++11 -o CMakeFiles/vx_nn.dir/src/kernels.cpp.o -c /home/amd/amdovx-modules/vx_nn/src/kernels.cpp
c++: error: unrecognized command line option ‘-h’
vx_nn/CMakeFiles/vx_nn.dir/build.make:62: recipe for target 'vx_nn/CMakeFiles/vx_nn.dir/src/kernels.cpp.o' failed
make[2]: *** [vx_nn/CMakeFiles/vx_nn.dir/src/kernels.cpp.o] Error 1
make[2]: Leaving directory '/home/amd/amdovx-modules/build'
CMakeFiles/Makefile2:405: recipe for target 'vx_nn/CMakeFiles/vx_nn.dir/all' failed
make[1]: *** [vx_nn/CMakeFiles/vx_nn.dir/all] Error 2
make[1]: Leaving directory '/home/amd/amdovx-modules/build'
Makefile:127: recipe for target 'all' failed

Any idea what I may be missing? 
It looks like it is adding unnecessary -hc -fPIC to the compiler which is failing. Could not find in CMAKEFILE where we are adding this. Any help appreciated.

Prakash

**Comment by srp1970** [comment]
Resolved this. I think the issue was that I had not build dependencies correctly. Works now.

**Comment by rgiduthuri** [comment]
Closing as the issue has been resolved by @srp1970
