### ISSUE TITLE
 ERROR: clBuildProgram(0x1229890,-cl-std=CL2.0) failed(-11) for com.amd.loomsl.calc_lens_distortionwarp_map

### ISSUE THREAD

**Issue by arpu** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#19]
with new update i get this error on intel beignet master 
(works fine with nvidia and  amd opencl) 

bugreport on beignet 
https://bugs.freedesktop.org/show_bug.cgi?id=101742

but maybe someone from amd have an idea

**Comment by rgiduthuri** [comment]
I'm not familiar with beignet. It will help, if you can point the actual line in OpenCL source that causes the clBuildProgram to fail.

**Comment by arpu** [comment]
works now on develop branch
