### ISSUE TITLE
Sample code for amdovx-modules

### ISSUE THREAD

**Issue by bnascimento** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#2]
Hi, do we have any sample code for how to run, amdovx-modules?
How does it integrate with runvx engine?

**Comment by rgiduthuri** [comment]
Hi, here is an example with medianblur kernel from vx_ext_cv module in amdovx-modules project:

```
import vx_ext_cv

data input = image:1280,720,U008
data ksize = scalar:VX_TYPE_INT32,7
data output = image:1280,720,U008

node org.opencv.medianblur input output ksize
```
