### ISSUE TITLE
Gaussian Blur Leaves Top and Bottom Rows Black

### ISSUE THREAD

**Issue by iggy14750** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#203]
Hello all,

Please forgive me if this is not the appropriate forum, but I was seeking some support in using this implementation of OpenVX. In using it, I have noticed that when putting an image through a Gaussian blur node, this leaves the top and bottom rows of the output image to be black (all zeros). In fact, I believe that this is the case for all convolutions implemented by this library, but I want to focus on Gaussian to make it simple.

Now, I am asking myself if this is expected behavior. I personally am not very familiar with image processing, but in speaking with others, and checking the OpenCV Gaussian implementation, this behavior is not normal for a convolution.

I am asking for advice as to whether this is expected, or if you believe I have misused the library. If you would like help reproducing, I have a file which exhibits the behavior I am interested in, and will share it by the means most convenient for you.

Please contact me directly at isaac@concurrenteda.com if you would prefer.

**Comment by kiritigowda** [comment]
Hi @iggy14750 can you please share the test case with me. Thanks!

**Comment by lcskrishna** [comment]
@iggy14750 

You might be hitting the border modeof the spec if you haven't set it explicitly.
 By default the border mode is set to undefined. 
Please refer to this part of spec [Link](https://www.khronos.org/registry/OpenVX/specs/1.2.1/html/index.html#sec_valid_region)

**Comment by kiritigowda** [comment]
@iggy14750 hope @lcskrishna comment helps with the problem you had. Please do file another bug if you still think there is a problem and provide a test case so we can reproduce the issue and fix it.
