### ISSUE TITLE
ERROR: vxGetKernelByName(context,"com.amd.nn_extension.convert_image_to_tensor") failed (-12:VX_ERROR_INVALID_REFERENCE)

### ISSUE THREAD

**Issue by peter-zigo-nxp** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#208]
Hello, 

I looking for help with vx_nn example 1: from 
https://github.com/GPUOpen-ProfessionalCompute-Libraries/amdovx-modules/blob/develop/vx_nn/README.md

I getting error message after run command in ./runvx shell 
runvx 0.9.9
OK: using AMD OpenVX 0.9.9
% com.amd.nn_extension.convert_image_to_tensor
ERROR: syntax error: com.amd.nn_extension.convert_image_to_tensor 
See help for details.
% node com.amd.nn_extension.convert_image_to_tensor
ERROR: vxGetKernelByName(context,"com.amd.nn_extension.convert_image_to_tensor") failed (-12:VX_ERROR_INVALID_REFERENCE)

Environment description:
Virtual ubuntu 16.04 
CPU Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz

**Comment by paveltc** [comment]
I have run the test and did not see the error that you are reporting.
I have attached the example with an image to this comment. Please try with the new files and see if you have the same issue.

[Example1.tar.gz](https://github.com/GPUOpen-ProfessionalCompute-Libraries/amdovx-modules/files/2385215/Example1.tar.gz)

**Comment by peter-zigo-nxp** [comment]
Hi,
I tried your example, but from message below I can't load libvx_nn.so.
Also I added lib path libvx_nn.so to LD_LIBRARY_PATH, but this didn't help.

./runvx example1.gdf
runvx 0.9.9
OK: using AMD OpenVX 0.9.9
ERROR: Unable to load module libvx_nn.so
ERROR: vxLoadKernels(context,"vx_nn") failed (-11:VX_ERROR_INVALID_MODULE)

**Comment by peter-zigo-nxp** [comment]
Hi,
I tried your example, but from message below I can't load libvx_nn.so.
Also I added lib path libvx_nn.so to LD_LIBRARY_PATH, but this didn't help.

./runvx example1.gdf
runvx 0.9.9
OK: using AMD OpenVX 0.9.9
ERROR: Unable to load module libvx_nn.so
ERROR: vxLoadKernels(context,"vx_nn") failed (-11:VX_ERROR_INVALID_MODULE)

????

**Comment by kiritigowda** [comment]
@peter-zigo-nxp I have attached 2 scripts which will setup the deps for this project and build the project and installs.

Please follow the steps below after you unzip the files in the scripts.zip

* Step 1: Run the setup.py script
````
python setup.py -s [sudo password] -d [setup directory - optional] 
````

* Step 2: Run the build.py scipt
````
python build.py -s [sudo password] -d [build directory - optional]
````
* Step 3: Set Library path
````
.  rocmrc
````
* Step 4: Run the example
````
runvx example1.gdf
````
[scripts.zip](https://github.com/GPUOpen-ProfessionalCompute-Libraries/amdovx-modules/files/2426160/scripts.zip)

**Comment by kiritigowda** [comment]
@peter-zigo-nxp it looks like you are not building the vx_nn project due to dependency failure. Please check if you have libvx_nn.so in the lib folder, if not just follow the instructions in the previous comment.

**Comment by kiritigowda** [comment]
@peter-zigo-nxp I am closing this issue as it is not an amdovx-modules bug. If you still have build issues please open a new bug with the deps failure.
