### ISSUE TITLE
Will this library work with RX 470 ?

### ISSUE THREAD

**Issue by boxerab** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#21]

**Comment by paveltc** [comment]
It should work functionally. It depends on the configuration you use. What are you using it for?

**Comment by boxerab** [comment]
Thx, what do you mean by the configuration? I have two 470s btw.

**Comment by paveltc** [comment]
How many cameras are you using and at what resolution is each camera?

**Comment by boxerab** [comment]
well, I don't have any cameras : just interested in researching this project. Is there sample footage I can play around with, or a way of generating this ?

**Comment by rgiduthuri** [comment]
The OpenVX uses standard OpenCL as underlying library. Since all RX 470 supports OpenCL, it should work fine.

**Comment by boxerab** [comment]
@rgiduthuri  there is still an unanswered question in the comments. I will open in separate issue.
