### ISSUE TITLE
Running Loom Shell Ubuntu 18.04 Rx 580

### ISSUE THREAD

**Issue by ghost** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#215]
I cannot find the Loom_shell.exe file. I tried going to amdovx-modueles-master/utils/loom_shell but no luck. I followed the readme and installed all the necessary parts. when I tried to build the loom_shell.sln in VS I keep getting this: Terminal will be reused by tasks, press any key to close it.

> Executing task: msbuild /property:GenerateFullPaths=true /t:build <

/bin/bash: msbuild: command not found
The terminal process terminated with exit code: 127

Terminal will be reused by tasks, press any key to close it.

I can't figure out how to get it running. Can anyone help maybe explain this a little more clearly for linux?

**Comment by kiritigowda** [comment]
@winsteadworks I am linking you to the project to help you setup & build on Linux.

https://github.com/kiritigowda/Radeon-MIVision-setup

**Comment by ghost** [comment]
Ok thank you for the reply. I am going to check it out right now

**Comment by kiritigowda** [comment]
@winsteadworks hope this solved your issue. I am going to mark this issue as closed. If you are still having any specific problem, please open a new issue.
