### ISSUE TITLE
 Is there sample footage I can use, or a way of generating this ?

### ISSUE THREAD

**Issue by boxerab** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#23]
I don't have any cameras at the moment, but I would like to see how the library functions.
So, can I simulate camera footage, or generate synthetic footage ?

**Comment by kiritigowda** [comment]
Hi @boxerab you can use the example images from [here ](https://www.ptgui.com/images/vigntutorial/vigntutorial.zip) along with the attached loom shell script.
[PTgui.txt](https://github.com/GPUOpen-ProfessionalCompute-Libraries/amdovx-modules/files/1177643/PTgui.txt) or reference the closed issue #15

**Comment by boxerab** [comment]
Great, thank you!
