### ISSUE TITLE
loom example

### ISSUE THREAD

**Issue by cvaldesmol** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#3]
Hi there,
Is there any example or short guide on how to use loom? Thanks

**Comment by rgiduthuri** [comment]
I will post them in few days.

**Comment by rgiduthuri** [comment]
Please let me know if the README.md in loom_shell and vx_loomsl are good enough.

**Comment by cvaldesmol** [comment]
Thanks. It looks good.
It would be nice to have an example for the most used 6 camera rig with wide angles and not only for circular fisheye.
