### ISSUE TITLE
is loom locked to amd cards?

### ISSUE THREAD

**Issue by cvaldesmol** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#4]
Hi
openvx is a layer that can connect to cpu and gpu cards. loom uses openvx. I wonder if loom code is only for amd graphic cards or we can use any other brand. Thanks

**Comment by rgiduthuri** [comment]
Current implementation uses OpenCL with few AMD specific extensions. It can be ported to other GPUs with OpenCL support.
