### ISSUE TITLE
[Question] How do use UMat from opencv as input and output ? 

### ISSUE THREAD

**Issue by arpu** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#50]
is it possible to use UMat (from Gpu memory) as inpout/output to the live stitching api?

**Comment by rgiduthuri** [comment]
Don't have experience with UMat. Live stitch api expects input/outputs to be OpenCL buffers (cl_mem). Try exporting UMat handle to OpenCL buffer (cl_mem).

**Comment by arpu** [comment]
ok i found i can convert the umat to cl_mem with 
(loading a image is a sample)
cv::UMat img = cv::imread( "cam00.jpg", cv::IMREAD_COLOR  ).getUMat( cv::ACCESS_RW );
buf[0] = (cl_mem)img.handle(cv::ACCESS_RW);          

but  lsSetCameraBuffer(context, &buf[0]); needs more images (buffer)  
i looking at loadBuffer() but this only loads the buffer from a file

any hints? to load the correct buffer for  lsSetCameraBuffer  (4 cameras)

**Comment by rgiduthuri** [comment]
Unfortunately, the current API accepts all input images in one buffer.
Try allocating a larger buffer and use clEnqueueCopyBuffer to copy from individual UMat into one large cl_mem.

**Comment by rgiduthuri** [comment]
please reopen if the above comment doesn't address the issue

**Comment by arpu** [comment]
i get  openclerror -34
-34 | CL_INVALID_CONTEXT |   | if context is not a valid context.

err  = clEnqueueCopyBuffer(cmdq, (cl_mem)img0.handle(cv::ACCESS_RW), buf[0],
                                               srcrawofs, 0, total, 0, 0, 0);
        std::cout << err << std::endl; 

so the problem looks like opencv and openvx use different context?

**Comment by sferenz** [comment]
Basically every application has its own context. As far as I understood you, you want to use the Loom extension, you should try the following:
1. Create an OpenCL context (cl_context)
2. Copy with clEnqueueCopyBuffer
3. Create an Loom Context (ls_context)
4. Give the cl context to Loom (lsSetOpenCLContext)

**Comment by arpu** [comment]
yes but the problem is i  want use the opencv UMat (opencl mem)  (cl_mem)img0.handle(cv::ACCESS_RW)

**Comment by sferenz** [comment]
OpenCV has a function to use an external cl_context:
- OpenCV 2.4: initializeContext(void* pClPlatform, void* pClContext, void* pClDevice) http://docs.opencv.org/2.4/modules/ocl/doc/structures_and_utility_functions.html
- OpenCV 3.0: initializeContextFromHandle( Context & ctx, void * platform, void *context, void * device) http://docs.opencv.org/3.2.0/d1/d45/classcv_1_1ocl_1_1Context.html


Try to create the OpenCV context that way and use the same context for the copy.

**Comment by arpu** [comment]
i cannot get this working :/ next problem looks like the opencl command Queue
maybe you have time to look at my test source
[Source_UMat.zip](https://github.com/GPUOpen-ProfessionalCompute-Libraries/amdovx-modules/files/1308402/Source_UMat.zip)

**Comment by rgiduthuri** [comment]
I'm curious about OpenCL configuration. Please attach output of clinfo.

**Comment by arpu** [comment]
clinfo on fedora 26  with nvidia closed source driver
http://lpaste.net/2028051821657849856

**Comment by arpu** [comment]
but this does not have any OpenCL configuration problem? if its needed i can test with 
a amd gpu

**Comment by sferenz** [comment]
Can you please try the following order:
1) Get cl_context from loom
2) Initialize cl_context to OpenVX
3) Create ocl buffers
4) Do OpenVX operation
5) Copy from ocl to cl_mem for LOOM
6) Do Loom

If there is still an error, please post it here.

**Comment by arpu** [comment]
i get always error -34 on clEnqueueCopyBuffer
-34 error means CL_INVALID_CONTEXT
i use the opencl_context from the lsGetOpenCLContext and build the cl_command_queue with
cl_command_queue cmdq = clCreateCommandQueue((cl_context)opencl_context, (cl_device_id)cv::ocl::Device::getDefault().ptr(),  0, nullptr);

**Comment by rgiduthuri** [comment]
Looking at the error message, I'm guessing that the OpenCV and LOOM are using different OpenCL contexts.
Make sure that all the modules are using same OpenCL context. You can get set the request the LOOM to use a particular OpenCL context by using below API:

`vx_status lsSetOpenCLContext(ls_context stitch, cl_context opencl_context);`

Make sure to call this API immediately after creating the `ls_context`.

**Comment by arpu** [comment]
thx a lot for your time 
it works now for me! with 
http://lpaste.net/359427 if someone else need this

the only problem now is the output looks strange in the colors (using nvidia card) 
should i open a seperate bugreport for this? 
https://drive.google.com/file/d/0B1Gn13Bs6VLTMkdtSXBYczBFTUU/view?usp=sharing

**Comment by arpu** [comment]
this is on branch  develop

**Comment by rgiduthuri** [comment]
Do you have a loom_shell test script that can reproduce this problem?

**Comment by arpu** [comment]
yes its with every sample i found 
OpenVX using GPU device#0 (GeForce GTX 1060 6GB) [OpenCL 1.2 CUDA] [1]
same on intel 
output 
http://lpaste.net/359430


[github_test.zip](https://github.com/GPUOpen-ProfessionalCompute-Libraries/amdovx-modules/files/1404448/github_test.zip)

**Comment by arpu** [comment]
any news on this? or should i open a separate bug report?

**Comment by rgiduthuri** [comment]
Looks like this issue is related to non-AMD hardware. It will be good to file a new issue for this problem and close this issue.

**Comment by arpu** [comment]
back on this with a amd GPU 
clinfo: https://gist.github.com/arpu/48f9b182e1126601829bcdfb556b67d8
i can copy the image with clEnqueueCopyBuffer without any error but the resulting img looks wrong 

sourcecode: https://gist.github.com/arpu/7dec7fbd25f4b428274877015d011375 

for the  initializeContextFromHandle i had to patch opencv to export this 
(https://github.com/opencv/opencv/issues/10714)

add CV_EXPORTS to https://github.com/opencv/opencv/blob/3.4.0/modules/core/include/opencv2/core/ocl.hpp#L322

added source images and sourcecode + outputimage 
[amd_loom.zip](https://github.com/GPUOpen-ProfessionalCompute-Libraries/amdovx-modules/files/1674748/amd_loom.zip)

**Comment by arpu** [comment]
here is the console output 
OPENCV_OPENCL_DEVICE=:GPU:0
[ INFO:0] Initialize OpenCL runtime...
Host memory: 0
clCreateCommandQueue:0
[ INFO:0] Successfully initialized OpenCL cache directory: /home/arpu/.cache/opencv/3.4.0-dev/opencl_cache/
[ INFO:0] Preparing OpenCL cache configuration for context: Advanced_Micro_Devices__Inc_--Baffin--2527_3
sizeinBytes9437184
total9437184
0
0
0
0
..showCameraConfig: cameras:4x1 format:RGB2 buffer:2048x6144
..showCameraConfig: index#0 {{  71.577,   1.857, -88.089,0,0,0},{183.232,2086.0,1043.0,7.000,20.000,ptgui_lens_fisheye_circ,-0.167732,-0.041492,0.027047}};
..showCameraConfig: index#1 {{ 160.129,   1.720, -89.239,0,0,0},{183.232,2086.0,1043.0,7.000,20.000,ptgui_lens_fisheye_circ,-0.167732,-0.041492,0.027047}};
..showCameraConfig: index#2 {{-108.202,   1.994, -91.499,0,0,0},{183.232,2086.0,1043.0,7.000,20.000,ptgui_lens_fisheye_circ,-0.167732,-0.041492,0.027047}};
..showCameraConfig: index#3 {{ -18.478,   1.719, -90.532,0,0,0},{183.232,2086.0,1043.0,7.000,20.000,ptgui_lens_fisheye_circ,-0.167732,-0.041492,0.027047}};
..showOutputConfig: format:RGB2 buffer:3840x1920
OK: created output.bmp
> stitch graph profile
 COUNT,tmp(ms),avg(ms),min(ms),max(ms),DEV,KERNEL
     1,  6.327,  6.327,  6.327,  6.327,CPU,GRAPH
     1,  6.316,  6.316,  6.316,  6.316,GPU,com.amd.openvx.Remap_U24_U24_Bilinear
LOG:[status=0] OK: OpenCL buffer usage: 147456544, 3/3

**Comment by arpu** [comment]
i think i found a better solution with help from alalek (opencv dev) 
best is to use opencv cv::ocl::attachContext()

after some more testing i will close this

**Comment by arpu** [comment]
https://docs.opencv.org/3.4.0/dc/d83/group__core__opencl.html#gaf83af36be2097fd43e3eba5c8f3025b1
works perfect so i close this
