### ISSUE TITLE
3rd party LoomIO plug-ins

### ISSUE THREAD

**Issue by cvaldesmol** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#6]
HI there
Where can I get the io plugins ? 3rd party LoomIO plug-ins?
Is that the way to get the video and turn it into frames?
I want to test with live and offline video. Do you support both?

**Comment by rgiduthuri** [comment]
Hi,
Yes, the LoomIO plug-in architecture is designed to get input frames directly into the stitching pipeline. I will post LoomIO documentation soon so that anybody can build these plug-ins themselves.

**Comment by cvaldesmol** [comment]
Great. Thanks. It would be nice to see offline processing as well. Something like open videos, get frames, process frames and write 360 to video file.
