### ISSUE TITLE
found a bug in multiband_blend_opencl_codegen line 228

### ISSUE THREAD

**Issue by cha007** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#67]

**Comment by sferenz** [comment]
Can you provide some more information?

- On which branch are you working? 
- Which platform do you use?
- What error message do you see?

**Comment by cha007** [comment]
1 i work on the branch from this https://github.com/cha007/amdovx-core
2 i use amd R9 390
3 this is not a error but the top part of the first image is lost , because the op_buf is not big enough to hold the value read from wt_buf.
all the input image is 1920*1080
[bug.zip](https://github.com/GPUOpen-ProfessionalCompute-Libraries/amdovx-modules/files/1287450/bug.zip)

**Comment by cha007** [comment]
and if i set context->isAmdMediaOpsSupported = false; my result is not right
i change this agoEmulateAmdMediaOpsInOpenCL 
			"uint amd_bytealign(uint src0,uint src1, uint src2){\n"
			"	uint dst = (uint)(as_ulong((uint2)(src1,src0)) >> (src2 & 31) * 8 );\n"
			"	return dst;\n"
			"}\n"
to
			"uint amd_bytealign(uint src0,uint src1, uint src2){\n"
			"	uint dst = (uint)(((((long)src0) << 32) | (long)src1) >> ((src2 & 3) * 8));\n"
			"	return dst;\n"
			"}\n"
will fine.

**Comment by rgiduthuri** [comment]
Looks like there are some platform related issues when amd media ops is not supported. 

Could you please try with the latest from develop branch?

**Comment by rgiduthuri** [comment]
Pushed the latest develop to master. Please try and reopen the issue if problem persists.
