### ISSUE TITLE
full frame lense usage

### ISSUE THREAD

**Issue by cvaldesmol** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#7]
If I do not use a circular fisheye, what should I put on:
 r_crop, du0 and dv0? is zero ok?

**Comment by rgiduthuri** [comment]
r_crop is meant for circular fisheye. You should set it to zero for other lens types.  I should update the header file to reflect the same.
The du0 and dv0 can be non-zero depending on lens alignment with camera.
