### ISSUE TITLE
how to read frames and write video file

### ISSUE THREAD

**Issue by cvaldesmol** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#8]
Hi there
I see that in the code the input is image files and the output is a file as well. Are you going to provide the libraries to read from a video directly (offline video / video files)? Are you going to create the libaries to write the output to video mp4 ?
Thanks

**Comment by rgiduthuri** [comment]
Loom architecture has a mechanism for 3rd parties to build camera capture plug-in modules, which can be used to read images from video files. 
See Wiki page for tutorial slides on LoomIO plug-ins.
https://github.com/GPUOpen-ProfessionalCompute-Libraries/amdovx-modules/wiki

If you're interested to build a plug-in using ffmpeg libraries for reading from video files, I may be able to help you.

**Comment by cvaldesmol** [comment]
Sorry for the late reply. I was away on holidays. 
We would like to build the plug-in but do not think my boss will allow me to put it as open source. 
Are you able to help if it is a commercial plug-in? If you send me an email at cvaldesmol at gmail I can share with you what we have so far. Thanks

**Comment by kiritigowda** [comment]
@cvaldesmol were you able to get the plug-in to work?

**Comment by rgiduthuri** [comment]
Please try with #41
