### ISSUE TITLE
tensorflow to OpenVX graph

### ISSUE THREAD

**Issue by reger-men** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#81]
I think it would be advantageous if we would extend the function to generate OpenVX graph from tensorflow.

The extension of the function `inference_generator` is all what we need to adjust.
is someone interested in this functionality? I would like to hear the community opinion.

**Comment by rgiduthuri** [comment]
@reger-men I would love to see a python script for generating OpenVX graph from a pretrained tensorflow model.

**Comment by rgiduthuri** [comment]
Hi @reger-men, let me know if you need any help with the inference generator with tensorflow.

**Comment by reger-men** [comment]
Thanks @rgiduthuri, not yet.  But I will take you up on your offer ;)
