### ISSUE TITLE
Is it limited to AMD Pro cards and why?

### ISSUE THREAD

**Issue by tobi-tobsen** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#9]
Hi, 
this is really an interesting project - thank you for your efforts. 
In the prerequisites you write that a 

> Radeon W9100 16GB

is needed. I wonder why this is the case and if it could be working with consumer graphics cards (e.g. latest rx480) as well. 
If not, what is currently missing hardware and software wise?
Is it an artificial/intentional limitation (e.g. in the driver)?

**Comment by gshisha** [comment]
There is no restriction on using it on consumer cards (like RX480). We have qualified the product on the W9100 card extensively, so that's the main reason. Based on your use case, you may also have the following issues on the consumer cards.
1. Memory limitations (ususally only 4GB or 8GB available)
2. Direct-GMA not available for fast transfer of camera buffers.

**Comment by tobi-tobsen** [comment]
Thanks for the clarification and quick response. 
Is Direct-GMA a software feature (e.g. on the driver level) or is it dependent on certain hardware components not available on the other (consumer) cards?

**Comment by gstoner** [comment]
Currently DirectGMA is only support on FIrePro and Radeon Pro hardware
On Dec 17, 2016, at 4:42 AM, tobsen <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the clarification and quick response.
Is Direct-GMA a software feature (e.g. on the driver level) or is it dependent on certain hardware components not available on the other (consumer) cards?

**Comment by tobi-tobsen** [comment]
> Currently DirectGMA is only support on FIrePro and Radeon Pro hardware
Sorry for stressing this, but is it _supported_ because there are special hardware parts on those Pro cards for DirectGMA 
or is it theoretically feasible to get DirectGMA working on non-pro cards 
or would you rather not say?

**Comment by rgiduthuri** [comment]
Please refer to the following links for more details about DirectGMA:
https://www.amd.com/Documents/SDI-tech-brief.pdf
http://developer.amd.com/community/blog/2014/09/08/amd-firepro-gpus-directgma/

What's your camera configuration and the required PCIe bandwidth between camera capture cards and GPU?

**Comment by tobi-tobsen** [comment]
@rgiduthuri thanks for the additional links. 
I am currently evaluating the possibilities to connect multiple cameras to one pc while still having sub-frame latency at >=60hz and therefore cannot answer your question yet.
However, mine has been answered to some extend => closing this issue. Thanks for your responses.
