### ISSUE TITLE
BUG: Image to tensor and tesor to image for Grayscale images

### ISSUE THREAD

**Issue by reger-men** [GPUOpen-ProfessionalCompute-Libraries/amdovx-modules#98]
Tested with different files type. The output either of  **_tensor To image_**  or  **_image To tensor_**. Or both is/are damaged. [src](https://github.com/GPUOpen-ProfessionalCompute-Libraries/amdovx-modules/tree/master/vx_nn/src)

**in image to tensor kernel**: I don't thing that this line is correct: 
`uint x = get_global_id(0) * 4;`
We have to multiple Pixel value with a and add b:
`u4 = ur * a + b;`

Thanks.

**Comment by rgiduthuri** [comment]
Hi @reger-men, the OpenCL kernel processes four pixels per workitem in order to be able to write on 32-bit boundary. In this case 4 RGB pixels will take 3 32-bit values.

You can use a GDF like one below to verify that image-to-tensor immediately followed by tensor-to-image will get back the same image.
````
import vx_nn

data inp = image:32,32,RGB2
data tmp = tensor:4,{32,32,3,1},VX_TYPE_FLOAT32,0
data out = image:32,32,RGB2

data reverse = scalar:VX_TYPE_BOOL,0

data fwd_a = scalar:VX_TYPE_FLOAT32,0.00390625 # normalize using (1/256)
data fwd_b = scalar:VX_TYPE_FLOAT32,0.0
node com.amd.nn_extension.convert_image_to_tensor inp tmp fwd_a fwd_b reverse

data bwd_a = scalar:VX_TYPE_FLOAT32,256.0
data bwd_b = scalar:VX_TYPE_FLOAT32,0.0
node com.amd.nn_extension.convert_tensor_to_image tmp out bwd_a bwd_b reverse

read  inp image0.rgb
write tmp ztmp2.f32
write out zout2.rgb
compare out image0.rgb
````

Please reopen this issue, if you found a test that produces incorrect output.

**Comment by reger-men** [comment]
Thanks @rgiduthuri for your response. I mean actually the conversation for **U008** (Gray) images. The Kernel are not fully implemented and the data that the Kernel receive are corrupted. I can take a look at it and give you feedback. 

We don't need to reopen this issue.
